import type { ModuleDefinition, LessonManifest } from '@/types/lesson'

// ─── 22 Module Definitions ────────────────────────────────────
export const IF_ELSE_MODULES: ModuleDefinition[] = [
  {
    id: '01-motivation',
    part: 1,
    title: 'Motivation',
    titleBn: 'অনুপ্রেরণা',
    icon: 'Sparkles',
    route: '/lesson/01-motivation',
    estimatedMinutes: 5,
    type: 'intro',
    description: 'Get inspired with real-life decision-making parallels before diving in.',
  },
  {
    id: '02-declaration',
    part: 2,
    title: 'Lesson Declaration',
    titleBn: 'পাঠ ঘোষণা',
    icon: 'Flag',
    route: '/lesson/02-declaration',
    estimatedMinutes: 3,
    type: 'declaration',
    description: 'Official lesson announcement with animated title reveal.',
  },
  {
    id: '03-outcomes',
    part: 3,
    title: 'Learning Outcomes',
    titleBn: 'শিক্ষণ ফলাফল',
    icon: 'Target',
    route: '/lesson/03-outcomes',
    estimatedMinutes: 4,
    type: 'outcomes',
    description: 'What you will master by the end of this lesson.',
  },
  {
    id: '04-pre-test',
    part: 4,
    title: 'Pre-Assessment',
    titleBn: 'পূর্ব মূল্যায়ন',
    icon: 'ClipboardList',
    route: '/lesson/04-pre-test',
    estimatedMinutes: 10,
    type: 'quiz',
    description: 'Test your existing knowledge before the lesson begins.',
  },
  {
    id: '05-discussion',
    part: 5,
    title: 'Lesson Discussion',
    titleBn: 'পাঠ আলোচনা',
    icon: 'BookOpen',
    route: '/lesson/05-discussion',
    estimatedMinutes: 40,
    type: 'discussion',
    description: 'Main lesson content — video + live Python interpreter + guided problems.',
  },
  {
    id: '06-key-notes',
    part: 6,
    title: 'Key Notes',
    titleBn: 'মূল নোট',
    icon: 'StickyNote',
    route: '/lesson/06-key-notes',
    estimatedMinutes: 5,
    type: 'notes',
    description: 'Golden summary lines and essential concepts to remember.',
  },
  {
    id: '07-scope',
    part: 7,
    title: 'Scope',
    titleBn: 'পরিসর',
    icon: 'Layers',
    route: '/lesson/07-scope',
    estimatedMinutes: 5,
    type: 'scope',
    description: 'Where IF-ELSE is used throughout Python and real applications.',
  },
  {
    id: '08-practical',
    part: 8,
    title: 'Practical Uses',
    titleBn: 'ব্যবহারিক প্রয়োগ',
    icon: 'Wrench',
    route: '/lesson/08-practical',
    estimatedMinutes: 10,
    type: 'practical',
    description: 'Real Python programs you can run — login, grade calculator, and more.',
  },
  {
    id: '09-fun-facts',
    part: 9,
    title: 'Fun Facts',
    titleBn: 'মজার তথ্য',
    icon: 'Lightbulb',
    route: '/lesson/09-fun-facts',
    estimatedMinutes: 5,
    type: 'facts',
    description: 'Surprising and interesting facts about conditional logic in computing.',
  },
  {
    id: '10-tips',
    part: 10,
    title: 'Tips & Tricks',
    titleBn: 'টিপস ও কৌশল',
    icon: 'Zap',
    route: '/lesson/10-tips',
    estimatedMinutes: 6,
    type: 'tips',
    description: 'Smart coding habits and pro tips for writing clean IF-ELSE code.',
  },
  {
    id: '11-riddles',
    part: 11,
    title: 'Riddles',
    titleBn: 'ধাঁধা',
    icon: 'HelpCircle',
    route: '/lesson/11-riddles',
    estimatedMinutes: 8,
    type: 'riddles',
    description: 'Solve IF-ELSE riddles that test your logical thinking.',
  },
  {
    id: '12-story',
    part: 12,
    title: 'Story Learning',
    titleBn: 'গল্পে শেখা',
    icon: 'BookMarked',
    route: '/lesson/12-story',
    estimatedMinutes: 7,
    type: 'story',
    description: 'The Smart Shopkeeper — learn decision-making through narrative.',
  },
  {
    id: '13-games',
    part: 13,
    title: 'Learning Games',
    titleBn: 'খেলায় শেখা',
    icon: 'Gamepad2',
    route: '/lesson/13-games',
    estimatedMinutes: 15,
    type: 'games',
    description: 'Flashcards, board game concept, and online game links.',
  },
  {
    id: '14-worksheet',
    part: 14,
    title: 'Worksheet',
    titleBn: 'কর্মপত্র',
    icon: 'FileText',
    route: '/lesson/14-worksheet',
    estimatedMinutes: 20,
    type: 'worksheet',
    description: 'In-class practice worksheet — 50 marks, 4 sections.',
  },
  {
    id: '15-song',
    part: 15,
    title: 'Song / Rhyme',
    titleBn: 'গান / ছড়া',
    icon: 'Music',
    route: '/lesson/15-song',
    estimatedMinutes: 5,
    type: 'song',
    description: 'The IF-ELSE Song in English + Bengali rhyme (বাংলা ছড়া).',
  },
  {
    id: '16-vocabulary',
    part: 16,
    title: 'Vocabulary',
    titleBn: 'শব্দভান্ডার',
    icon: 'BookA',
    route: '/lesson/16-vocabulary',
    estimatedMinutes: 8,
    type: 'vocabulary',
    description: 'Advanced vocabulary with bilingual definitions and examples.',
  },
  {
    id: '17-problems',
    part: 17,
    title: 'Problem Solving',
    titleBn: 'সমস্যা সমাধান',
    icon: 'Code2',
    route: '/lesson/17-problems',
    estimatedMinutes: 30,
    type: 'problems',
    description: '15 scenario-based challenges from real-world Bangladesh contexts.',
  },
  {
    id: '18-post-test',
    part: 18,
    title: 'Post-Test',
    titleBn: 'উত্তর পরীক্ষা',
    icon: 'CheckSquare',
    route: '/lesson/18-post-test',
    estimatedMinutes: 15,
    type: 'quiz',
    description: 'Final assessment — 10 questions to measure what you learned.',
  },
  {
    id: '19-assignment',
    part: 19,
    title: 'Assignment',
    titleBn: 'অ্যাসাইনমেন্ট',
    icon: 'PenLine',
    route: '/lesson/19-assignment',
    estimatedMinutes: 30,
    type: 'assignment',
    description: 'Homework worksheet — 60 marks, 4 sections including MCQ.',
  },
  {
    id: '20-infographic',
    part: 20,
    title: 'Infographic',
    titleBn: 'ইনফোগ্রাফিক',
    icon: 'LayoutDashboard',
    route: '/lesson/20-infographic',
    estimatedMinutes: 5,
    type: 'infographic',
    description: 'Visual reference card summarizing all IF-ELSE concepts.',
  },
  {
    id: '21-jokes',
    part: 21,
    title: 'Jokes',
    titleBn: 'রসিকতা',
    icon: 'SmilePlus',
    route: '/lesson/21-jokes',
    estimatedMinutes: 3,
    type: 'jokes',
    description: 'Python programmer humor to lighten the mood.',
  },
  {
    id: '22-inspiration',
    part: 22,
    title: 'Inspirational Ending',
    titleBn: 'অনুপ্রেরণামূলক সমাপ্তি',
    icon: 'Star',
    route: '/lesson/22-inspiration',
    estimatedMinutes: 3,
    type: 'ending',
    description: 'Closing motivation — celebrate completing the lesson!',
  },
]

// ─── Lesson Manifest ──────────────────────────────────────────
export const IF_ELSE_LESSON: LessonManifest = {
  id: 'python-if-else',
  title: 'Python IF-ELSE Statements',
  titleBn: 'পাইথন IF-ELSE স্টেটমেন্ট',
  subtitle: 'From Basic to Advanced — Complete Interactive Lesson',
  totalModules: 22,
  totalMinutes: IF_ELSE_MODULES.reduce((sum, m) => sum + m.estimatedMinutes, 0),
  difficulty: 'Beginner',
  modules: IF_ELSE_MODULES,
}

// ─── Module helpers ───────────────────────────────────────────
export const getModuleById = (id: string) =>
  IF_ELSE_MODULES.find((m) => m.id === id)

export const getModuleByPart = (part: number) =>
  IF_ELSE_MODULES.find((m) => m.part === part)

export const getAdjacentModules = (id: string) => {
  const idx = IF_ELSE_MODULES.findIndex((m) => m.id === id)
  return {
    prev: idx > 0 ? IF_ELSE_MODULES[idx - 1] : null,
    next: idx < IF_ELSE_MODULES.length - 1 ? IF_ELSE_MODULES[idx + 1] : null,
  }
}
