export const ROUTES = {
  HOME: '/',
  LESSON_OVERVIEW: '/lesson',
  LESSON: (id: string) => `/lesson/${id}`,

  // Individual module routes
  MOTIVATION:    '/lesson/01-motivation',
  DECLARATION:   '/lesson/02-declaration',
  OUTCOMES:      '/lesson/03-outcomes',
  PRE_TEST:      '/lesson/04-pre-test',
  DISCUSSION:    '/lesson/05-discussion',
  KEY_NOTES:     '/lesson/06-key-notes',
  SCOPE:         '/lesson/07-scope',
  PRACTICAL:     '/lesson/08-practical',
  FUN_FACTS:     '/lesson/09-fun-facts',
  TIPS:          '/lesson/10-tips',
  RIDDLES:       '/lesson/11-riddles',
  STORY:         '/lesson/12-story',
  GAMES:         '/lesson/13-games',
  WORKSHEET:     '/lesson/14-worksheet',
  SONG:          '/lesson/15-song',
  VOCABULARY:    '/lesson/16-vocabulary',
  PROBLEMS:      '/lesson/17-problems',
  POST_TEST:     '/lesson/18-post-test',
  ASSIGNMENT:    '/lesson/19-assignment',
  INFOGRAPHIC:   '/lesson/20-infographic',
  JOKES:         '/lesson/21-jokes',
  INSPIRATION:   '/lesson/22-inspiration',
} as const
